installed_at: 2026-04-07T15:07:47.795Z
version: 0.1.0
files:
  rules:
    - README.md
    - common/agents.md
    - common/code-review.md
    - common/coding-style.md
    - common/development-workflow.md
    - common/git-workflow.md
    - common/hooks.md
    - common/patterns.md
    - common/performance.md
    - common/security.md
    - common/testing.md
    - cpp/coding-style.md
    - cpp/hooks.md
    - cpp/patterns.md
    - cpp/security.md
    - cpp/testing.md
    - csharp/coding-style.md
    - csharp/hooks.md
    - csharp/patterns.md
    - csharp/security.md
    - csharp/testing.md
    - golang/coding-style.md
    - golang/hooks.md
    - golang/patterns.md
    - golang/security.md
    - golang/testing.md
    - java/coding-style.md
    - java/hooks.md
    - java/patterns.md
    - java/security.md
    - java/testing.md
    - kotlin/coding-style.md
    - kotlin/hooks.md
    - kotlin/patterns.md
    - kotlin/security.md
    - kotlin/testing.md
    - perl/coding-style.md
    - perl/hooks.md
    - perl/patterns.md
    - perl/security.md
    - perl/testing.md
    - php/coding-style.md
    - php/hooks.md
    - php/patterns.md
    - php/security.md
    - php/testing.md
    - python/coding-style.md
    - python/hooks.md
    - python/patterns.md
    - python/security.md
    - python/testing.md
    - rust/coding-style.md
    - rust/hooks.md
    - rust/patterns.md
    - rust/security.md
    - rust/testing.md
    - swift/coding-style.md
    - swift/hooks.md
    - swift/patterns.md
    - swift/security.md
    - swift/testing.md
    - typescript/coding-style.md
    - typescript/hooks.md
    - typescript/patterns.md
    - typescript/security.md
    - typescript/testing.md
    - zh/README.md
    - zh/agents.md
    - zh/code-review.md
    - zh/coding-style.md
    - zh/development-workflow.md
    - zh/git-workflow.md
    - zh/hooks.md
    - zh/patterns.md
    - zh/performance.md
    - zh/security.md
    - zh/testing.md
  commands:
    - build-fix.md
    - code-review.md
    - plan.md
    - quality-gate.md
    - tdd.md
    - verify.md
  hooks:
    - check-hook-enabled.js
    - config-protection.js
    - pre-bash-commit-quality.js
    - quality-gate.js
  agents:
    - api-documenter.md
    - architect.md
    - build-error-resolver.md
    - code-reviewer.md
    - codebase-analyzer.md
    - data-analyst.md
    - dependency-mapper.md
    - document-reviewer.md
    - epic-optimizer.md
    - market-researcher.md
    - pattern-detector.md
    - planner.md
    - requirements-analyst.md
    - security-reviewer.md
    - tdd-guide.md
    - tech-debt-auditor.md
    - technical-decisions-curator.md
    - technical-evaluator.md
    - test-coverage-analyzer.md
    - trend-spotter.md
    - user-journey-mapper.md
    - user-researcher.md
